### ISSUE TITLE
[bug] Default API Key being rate-limited out of the box

### ISSUE THREAD

**Issue by AlvaroLuken** [rainbow-me/rainbowkit#1045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.11.0

### wagmi Version

0.11.x

### Current Behavior

Right out of the box, the Rainbow Kit makes a lot of POST requests without this being intended. We would like some way to disable these POST requests, as the error in the console can be very confusing for students using our projects that implement Rainbow Kit - enabled project to learn. Pic below:

![Screenshot 2023-02-21 at 5 56 56 PM](https://user-images.githubusercontent.com/25407127/220715290-fefaadb6-928d-4786-8e54-eca777197cd9.png)

### Expected Behavior

No default POST calls that are rate limited anyway without it being an intended behavior.

### Steps To Reproduce

Latest version of RK.

### Anything else?

For now, would love to learn some way of disabling these calls! Maybe a direct flag in the `chains` customization?

**Comment by DanielSinclair** [comment]
Hi @AlvaroLuken. This is because of the public API Key for the `alchemyProvider` was recently deprecated by Alchemy. An upcoming change to `create-rainbowkit` removes this default. In the meantime, you can just remove `alchemyProvider` in favor of `publicProvider` to rely on public nodes. That should clear up any console errors.

**Comment by AlvaroLuken** [comment]
Thank you, @DanielSinclair!!
