### ISSUE TITLE
brave wallet connection

### ISSUE THREAD

**Issue by Faraday26** [rainbow-me/rainbowkit#1072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^0.8.1

### wagmi Version

^0.10.11

### Current Behavior

I added the bravewallet exported from @rainbow-me/rainbowkit/wallets but it does not show up on the modal

### Expected Behavior

braveWallet should show up in the connection modal

### Anything else?

<img width="360" alt="image" src="https://user-images.githubusercontent.com/124781752/224300298-306cb5ca-6ca2-40bc-98b3-5597f32a4941.png">
<img width="183" alt="image" src="https://user-images.githubusercontent.com/124781752/224300490-d547aead-43d6-4f5d-a0b3-a1b2aa4d1b58.png">

**Comment by DanielSinclair** [comment]
@Faraday26 Brave will appear as an option only when using the Brave browser, but it seems like there is actually an issue with a recent release of Brave. Upon testing, `window.ethereum` is not being set by the browser's injector. Is Brave working for you across any other dApps right now?

**Comment by adbario** [comment]
@Faraday26 @DanielSinclair Not sure if related to this exact issue, but Brave also has some restrictions for providers: https://wallet-docs.brave.com/provider-availability/

**Comment by NakedFool** [comment]
> @NakedFool Are you bumping into this too? What extensions and wallets do you have active? MacOS/Windows/Linux? It appears like Brave shipped a buggy `v1.49.120 (Mar 9, 2023)` release.

Yes, one of our users reported that brave wallet does not function properly so I went ahead and installed both brave wallet and metamask on brave browser, I'm using Windows OS.

**Comment by DanielSinclair** [comment]
@NakedFool Unclear what changed here, but noticed a few things:
- Brave's `Web3 > Wallet > Default Ethereum wallet` setting now has different options between macOS and Windows. On Windows, you have the previous `Brave Wallet (prefer extensions)` default and on macOS you have `Brave Wallet` and `Extensions`, defaulting to `Brave Wallet`.
- Users can only see Brave when `Brave Wallet` is selected, and `Brave Wallet (prefer extensions)` or `Extensions` are selected but no extension is active. If `Extensions` is selected, users should still be able to interface with MetaMask.
- You'll get a console error when `Brave Wallet` is selected and MetaMask is active, because Brave (now?) blocks MetaMask `window.ethereum` overrides
```Uncaught TypeError: Cannot assign to read only property 'ethereum' of object '#<Window>'
    at s (inpage.js:1:50542)
    at r.initializeProvider (inpage.js:1:50942)
    at Object.<anonymous> (inpage.js:1:1104)
    at Object.<anonymous> (inpage.js:1:1165)
    at 1.../../shared/modules/provider-injection (inpage.js:1:1178)
    at i (inpage.js:1:254)
    at e (inpage.js:1:414)
    at inpage.js:1:431
```
- Neither MetaMask or Brave Wallet support the `window.ethereum.providers` standard, so there's no happy path to use these wallets simultaneously and users will have to switch that setting

**Comment by gakonst** [comment]
Bumping on this as well. Still unable to connect my Metamask even after changing defaults.

**Comment by DanielSinclair** [comment]
@gakonst Double checking this. Are you seeing any console errors from the injector? That seems to be the common pattern when Brave interferes

**Comment by gakonst** [comment]
![image](https://user-images.githubusercontent.com/17802178/228323934-6fbd79f8-ebfe-4716-b25e-4db3217ab0d0.png)

nope, no error, not even detected

**Comment by KholdStare** [comment]
Experiencing the same issue on brave as above. Only see the QR code. Also have Brave Wallet setting as "Extensions" by default.

I have had no problem using the bare Metamask Connector from Wagmi. Now switching to rainbowkit, and it doesn't work.

**Comment by KholdStare** [comment]
@gakonst @DanielSinclair Looks like upgrading my Brave Browser has fixed the issue.

**Comment by DanielSinclair** [comment]
Tested against macOS Brave `Version 1.50.121 Chromium: 112.0.5615.138 (Official Build) (arm64)` and the detection appears to be working as expected again. Will close this issue!
