### ISSUE TITLE
openAccountModal .then()

### ISSUE THREAD

**Issue by KosmosKey** [rainbow-me/rainbowkit#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.2

### wagmi Version

0.12.2

### Current Behavior

So i was playing around with rainbow kit and my goal was to make an API call after my wallet is connected. I know there is a wagmi provider that allows you to listen for isConnected , but my app has slightly different functionality. I want to see if there is any possible way to do async await for openAccountModal or any techniques i can use to make this happen.

I use NextJS for this

### Expected Behavior

I want to have any async await operations if possible for wallet connections.

**Comment by DanielSinclair** [comment]
@KosmosKey Relying on Wagmi hooks is the best solution. Extensions and providers like the Safe browser will connect without user intervention, so relying on the UI state will be unreliable. RainbowKit is a wrapper around Wagmi after all, so definitely lean on Wagmi state rather than RainbowKit state. If the application you're looking at is Sign-in with Ethereum or a similar flow, have a look at the [Custom Authentication](https://www.rainbowkit.com/docs/custom-authentication) API.
