### ISSUE TITLE
Failed to parse source map from (Rainbowkit and Wagmi)

### ISSUE THREAD

**Issue by KosmosKey** [rainbow-me/rainbowkit#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.2

### wagmi Version

0.12.6

### Current Behavior

When you install the latest version of wagmi, rainbowkit and ethers js it has webpack issues. It can't generate source maps for the dependencies.

This issue is happening on latest react version with typescript.

### Expected Behavior

This shouldn't block from generating source maps. If i were to disable source maps when running npm start it would be hard to debug errors in a react app.

### Steps To Reproduce

I have created a repo here: https://github.com/KosmosKey/wagmi-rainbow-kit-ts

1. Clone the repo
2. Run `npm i` and `npm start`
3. You will see bunch of errors `Failed to parse source map`

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/KosmosKey/wagmi-rainbow-kit-ts

### Anything else?

This is a brand new react typescript app.

**Comment by DanielSinclair** [comment]
Thanks for this reproducible example! The warnings you're seeing are unfortunately an expected behavior in Webpack 5, and result from the packages upstream from Wagmi and RainbowKit. There are a few `react-app-rewired` approaches to filter the modules inspected by `source-map-loader`, but the easiest/recommended path in Webpack 5 would be to just ignore these specific warnings like so: https://webpack.js.org/loaders/source-map-loader/#ignoring-warnings
