### ISSUE TITLE
[bug] Metamask Wallet connect not working in Metamask browser

### ISSUE THREAD

**Issue by lotinasa** [rainbow-me/rainbowkit#1181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.8

### wagmi Version

0.12.10

### Current Behavior

When there is Discord Widget Bot script in React app, Metamask wallet connect not working only in mobile Metamask browser on any Android mobile (on iPhone works).

When I click on MM wallet connect icon it stays like that and nothing happen.

### Expected Behavior

When I click on MM wallet connect icon it should connect wallet.

### Steps To Reproduce

Discord Widget Bot script is in YourComponent.tsx file on CodeSandbox
https://codesandbox.io/s/rainbowkit-create-typescript-app-forked-d8g6pn?file=/package.json
When remove script for Widget Bot it is working as expected.
This issue started with latest version of mobile Metamask v6.3.0 (1095) on Android.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/rainbowkit-create-typescript-app-forked-d8g6pn?file=/package.json

### Anything else?

![MM_mobile_android](https://user-images.githubusercontent.com/3956262/233359985-b825a53d-2225-406a-a591-94a42c4f9f3c.jpg)

**Comment by DanielSinclair** [comment]
Thanks for the reproducible example. I'm not sure we will find an easy solution here. Try to give `@widgetbot/react-embed` a try instead of the typical async script injection and iframe. This could be any number of issues that originates from MetaMask's dApp browser; there is a lot of complexity in how MetaMask injects the provider and communicates with the webview. That RainbowKit hangs tells me that the MetaMask provider is detected, but the RPC requests by Wagmi aren't receiving a response.

**Comment by lotinasa** [comment]
Thanks for the response! 
I've tried with `@widgetbot/react-embed` and the same behavior. Sometimes MM even receives connection and I can confirm it, but that doesn't reflect on UI (as you mentioned like Wagmi is not receiving a response). 
For now we disabled Discord widget on mobile MM, but if you have any idea how to work this out please let me know.
