### ISSUE TITLE
[bug] Error: Module not found: Can't resolve 'fs' in './node_modules/node-gyp-build'

### ISSUE THREAD

**Issue by markkucler** [rainbow-me/rainbowkit#1234]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.2

### Current Behavior

I encountered an error when running my Next.js project using npm run dev. The error message is as follows:

error - ./node_modules/node-gyp-build/node-gyp-build.js:1:0
Module not found: Can't resolve 'fs'

This error occurs during the execution of the npm run dev command and prevents the successful execution of the Next.js development server.

### Expected Behavior

I expected the Next.js project to run smoothly without any errors related to the 'fs' module. I followed the installation guide provided in the documentation, and I anticipated that the development server would start without any issues related to module resolution.

### Steps To Reproduce

- Create a new Next.js app using the command: npm init @rainbow-me/rainbowkit@latest my-nextjs-app
- Navigate to the project directory: cd my-nextjs-app
- Start the Next.js development server: npm run dev
- Observe the error message mentioned above during the execution of the development server

**Comment by DanielSinclair** [comment]
@markkucler Thanks for spotting this. This looks to be a hiccup with the v1 rollout. `ethers` previously bundled these polyfills, but the new alternative `viem` that Wagmi v1 has adopted does not. Opened a PR to fix our `create-rainbowkit` templates so that you won't bump into this in the future. #1236

In the meantime, you can amend your `next.config.js` like this to polyfill `fs` and other required Node modules
```
const nextConfig = {
  reactStrictMode: true,
  webpack: config => {
    config.resolve.fallback = { fs: false, net: false, tls: false };
    return config;
  },
};
```

**Comment by jxom** [comment]
✅
