### ISSUE TITLE
Rainbow is redirecting to trust wallet links url after signing the message request

### ISSUE THREAD

**Issue by A-M-H-F** [rainbow-me/rainbowkit#1242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

^1.0.0

### Current Behavior

When connecting through Trust wallet (Android/Ios), we get a connection, then when we request a sign confirmation, after signing Rainbow is redirect the user from the website (where rainbow id active) to Trust wallet links url.

### Expected Behavior

It should not redirect to Trust wallet Links url, this should only happen if Trust wallet not installed, and it should not happen if there is a play store or app store, and the redirection should happen only before connecting of course.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

addictivecryptogames.com

**Comment by A-M-H-F** [comment]
I will post later on on, where the redirection is coming from at (rainbow package)

**Comment by DanielSinclair** [comment]
Hi @A-M-H-F. RainbowKit relies on Universal Links to deep link a user into their wallet for the connection step, or signing steps (like sign message or sign transaction). That is expected behavior. Sometimes wallets aren't configured properly, and their Universal Link will redirect a user to the App Store, as an example. In other cases, Mobile Safari remembers a preference for specific Universal Links, and will override the default behavior. This is typically triggered when you open the wallet's Universal Link with Safari's "Open in New Tab" feature. Safari interprets this as a signal that you prefer to use Safari to interact with that link, versus the native app. This is an unfortunate limitation of iOS. You can always reverse this behavior by using the "Open in Trust Wallet" button in Safari, but it can be confusing for users who don't realize when they've triggered this. Let me know if that answers your question, or if you have further questions.

**Comment by A-M-H-F** [comment]
> Hi @A-M-H-F. RainbowKit relies on Universal Links to deep link a user into their wallet for the connection step, or signing steps (like sign message or sign transaction). That is expected behavior. Sometimes wallets aren't configured properly, and their Universal Link will redirect a user to the App Store, as an example. In other cases, Mobile Safari remembers a preference for specific Universal Links, and will override the default behavior. This is typically triggered when you open the wallet's Universal Link with Safari's "Open in New Tab" feature. Safari interprets this as a signal that you prefer to use Safari to interact with that link, versus the native app. This is an unfortunate limitation of iOS. You can always reverse this behavior by using the "Open in Trust Wallet" button in Safari, but it can be confusing for users who don't realize when they've triggered this. Let me know if that answers your question, or if you have further questions.

thanks, this the answer i need.
