### ISSUE TITLE
[bug] recreating a connectors list breaks the Connection button

### ISSUE THREAD

**Issue by bulgakovk** [rainbow-me/rainbowkit#1265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.0

### wagmi Version

1.0.5

### Current Behavior

If you recreate a connectors list, it disrupts the connection flow, requiring a page refresh to display the connected wallet address after connecting to it.

https://user-images.githubusercontent.com/8983736/236782094-eb9814e2-40e5-4a07-8363-8631c54eff20.mov

### Expected Behavior

The wallet address should be visible immediately after connecting to it.

### Steps To Reproduce

Please see a Github repository with a PoC below.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/bulgakovk/connect-button-PoC

### Anything else?

When I was debugging the issue, I've noticed that `useConnectionStatus` hook doesn't update its value [there](https://github.com/rainbow-me/rainbowkit/blob/1de820368d7c3b312f631d0fead68f572830e1a8/packages/rainbowkit/src/components/ConnectButton/ConnectButton.tsx#L41) so that's why [that](https://github.com/rainbow-me/rainbowkit/blob/1de820368d7c3b312f631d0fead68f572830e1a8/packages/rainbowkit/src/components/ConnectButton/ConnectButton.tsx#L69) condition will be false and the connected wallet will not be displayed immediately.

 I've tried to distillate the Wagmi only part to a separate branch: https://github.com/bulgakovk/connect-button-PoC/tree/bulgakovk/feat/drop-rainbowkit-dependency (since `useConnectionStatus` depends on `useAccount` hook from Wagmi). But the Wagmi hook seems to be working fine on [that line](https://github.com/bulgakovk/connect-button-PoC/blob/3ed426b85c27a83ade75fc6556ad432f590a89f3/src/App.tsx#L9).

A rationale for updating the connectors list could be found there: [Wallet Standard connector request](https://github.com/wagmi-dev/references/discussions/273). Essentially, Standard Wallets possess an asynchronous registration (injection) API, which allows for the wallets list to be updated dynamically, and as a result, the connectors should be updated.

**Comment by DanielSinclair** [comment]
@bulgakovk Thanks for the detailed report here. This leans towards expected behavior currently as this is an atypical use of Wagmi, and the connector architecture has historically been designed to prepare connectors only once on page load. But I'll leave this open to see if it is possible to resolve this side effect without diverging from that architecture design. I'm not quite convinced that recreating the connector list is the correct end-goal or a viable approach for Wallet Standard connectors. We would instead need a deeper refactor where a single connector communicates with all Wallet Standard-supporting providers, and the 1-to-1 coupling of connectors to wallets would need to be deprecated. The standards are still waiting to be settled between EIP-5749/EIP-6963 and Wallet Standard, so we likely won't move forward here for a little while.

**Comment by KosmosKey** [comment]
@bulgakovk Are you still seeing this issue on your end ? If not we can close this issue.
