### ISSUE TITLE
[bug] When using RainbowKit to connect on web via mobile wallet, EIP1193 standard is not follows

### ISSUE THREAD

**Issue by Andriy-Kulak** [rainbow-me/rainbowkit#1337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.3

### wagmi Version

1.3.2

### Current Behavior

I am noticing that when I use rainbowkit, if I connect via a browser wallet like metamask, then the EIP 1193 standard is followed where I can see what address is connected via `window.ethereum.selectedAddress`
however if a user is using a mobile wallet like wallet connect or rainbow kit to connect to a website on desktop then the EIP 1193 standard is not followed & I cannot use browser window object to understand which wallet is connected.

Why is this the case & how can I figure out what address is connected without using wagmi?

### Expected Behavior

follow EIP standard across all wallets browser & mobile when connecting to browser website Some scripts cannot rely on wagmi to check if address is connected.

### Steps To Reproduce

Use rainbow kit using a react, connect via mobile wallet app like rainbow wallet. You will notice that `window.ethereum.selectedAddress` even though you connected

**Comment by DanielSinclair** [comment]
Hi @Andriy-Kulak. You're correct that `window.ethereum` won't be populated by WalletConnect connectors. This is by design. This is where Wagmi comes in. RainbowKit is built on top of Wagmi and Wagmi's connectors, and helps the dApp open an RPC session with one of the wallet connectors (whether an injected wallet, walletconnect, or otherwise). Then Wagmi's hooks can be utilized to interact with the wallet, or get information like the connected address. You'll want to always rely on Wagmi as the source of truth in your component state tree, as users can disconnect wallets, switch networks, switch accounts, etc.

Here is how you would fetch the selected/active wallet address in the Wagmi paradigm:
```tsx
const { address } = useAccount()
```

Let me know if this is helpful. There is usually always a way to rely on Wagmi, even if you're dropping RainbowKit and Wagmi into a pure HTML project.

**Comment by Andriy-Kulak** [comment]
@DanielSinclair can you provide an example of what event I can hook into to get notified when a user is connected in a pure HTML experience? I looked through wagmi documentation but couldn't find anything since wagmi is focusing on being a react hooks library.

**Comment by DanielSinclair** [comment]
@Andriy-Kulak Here is an [HTML example](https://codesandbox.io/s/rainbowkit-html-mhecor) that uses a traditional React setup and then Webpack to bundle the script so that it could be hosted and injected with `<script>`. This follows the standard path described [here](https://react.dev/learn/add-react-to-an-existing-project) to use React alongside other DOM elements or DOM manipulating scripts. But you're leaving best practices at this point and will need to manage communication/events/listeners between your elements and Wagmi's hooks (implemented in the bundle) with a global like `window`. Wagmi does offer the `wagmi/core` library as a way to expose the non-React innerworkings, but RainbowKit doesn't directly support this and the React hooks are a better development paradigm for reactive web3 apps.
