### ISSUE TITLE
[bug] closing of connect modal can't be controlled

### ISSUE THREAD

**Issue by saitejas-cypherd** [rainbow-me/rainbowkit#1360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.4

### wagmi Version

1.3.3

### Current Behavior

When we reject the connection request, we are not able to close the modal

### Expected Behavior

When we reject the connection request, we should be able to close the modal. Basically we need a control to close the connect modal

### Steps To Reproduce

1) Connect to app.cypherwallet.io through walletconnect
2) Reject the connection request
3) The connection modal is still open (which is expected to close which currently can't be done)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://app.cypherwallet.io

**Comment by DanielSinclair** [comment]
Hi @saitejas-cypherd. The expected behavior currently is actually that the modal should remain open after a user rejects the request, as they can then try again or select a different wallet. The modal state is currently controlled by the user for a better UX, because it could be easy to inadvertently degrade the UX by flashing modals open and closed while a user is trying to complete an action. That being said, we should provide some level of customizability here. Please leave feedback in this discussion of what your usecase is and what a good dev UX could look like: #1347
