### ISSUE TITLE
[bug] Seeing WalletConnect error: To use QR modal, please install @walletconnect/modal package

### ISSUE THREAD

**Issue by moaazsidat** [rainbow-me/rainbowkit#1423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.0.4

### wagmi Version

1.3.4

### Current Behavior

Seeing an excessive amount of `To use QR modal, please install @walletconnect/modal package` errors 

### Expected Behavior

If I understand correctly, this should be handled in Rainbowkit, and not added as a dependency on applications using Rainbowkit?

**Comment by DanielSinclair** [comment]
@moaazsidat Can you share a reproducible example for me to diagnose? Please also reference our [Build tooling setup](https://www.rainbowkit.com/docs/installation#additional-build-tooling-setup) docs and the linked examples to ensure that your framework is configured properly for the Wagmi and WalletConnect bundler needs. Most of these issues arise upstream in WalletConnect's libraries and unfortunately we can't bundle all of these dependencies with RainbowKit directly.

**Comment by beilunyang** [comment]
It's not a rainbow bug.  This is due to the failure of the `@walletconnect/ethereum-provider` library to dynamically import `@walletconnect/modal`.  https://github.com/WalletConnect/walletconnect-monorepo/blob/eac72b9488c1b61751063aa6c97491926b293f3a/providers/ethereum-provider/src/EthereumProvider.ts#L526
