### ISSUE TITLE
[bug] Can't connect on Gnosis with Rainbow wallet

### ISSUE THREAD

**Issue by n1c01a5** [rainbow-me/rainbowkit#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^1.0.7

### wagmi Version

~1.3.9

### Current Behavior

When I scan the Rainbow QrCode I got this error "Connection Failed" on my mobile.

And get this error in my browser console :

```
client.js:1 Error: Invalid session settle request.
    at eval (index.es.js:1:3439)
    at async n (index.es.js:1:3258)
```

### Expected Behavior

Connect with Rainbow wallet

### Steps To Reproduce

On a local env, scan QR code.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

[Codesandbox](https://codesandbox.io/p/sandbox/nostalgic-christian-98f5pd?file=/pages/_app.tsx:9,43)

### Anything else?

Probably [Gnosis Chain is not supported](https://learn.rainbow.me/supported-networks) .

But it's not explicit in the README.

**Comment by BLOCKCHAINDEVWEB** [comment]
https://github.com/rainbow-me/rainbowkit/issues/1323

**Comment by DanielSinclair** [comment]
@n1c01a5 That's correct, Gnosis Chain is not currently supported by the Rainbow Wallet. Wallets that do support the network will work fine. There will soon be a change to WalletConnect v2 by the WalletConnect team that smooths out this problem because a WalletConnect session can now succeed even if none of the 'required' networks are supported. Currently Wagmi takes the first chain and marks it as 'required' for the WalletConnect session, causing the session to fail if the network is unsupported; now every network will be treated as `optional` and pass the error handling purely to the dApp side.

**Comment by jtrein** [comment]
@DanielSinclair I have this same issue locally, but when attempting to connect to Goerli. Very strange. I am using wagmi@1.3.9 as well.

**Comment by CondeGil** [comment]
> @n1c01a5 That's correct, Gnosis Chain is not currently supported by the Rainbow Wallet. Wallets that do support the network will work fine. There will soon be a change to WalletConnect v2 by the WalletConnect team that smooths out this problem because a WalletConnect session can now succeed even if none of the `required` networks are supported. Currently Wagmi takes the first chain and marks it as `required` for the WalletConnect session, causing the session to fail if the network is unsupported; now every network will be treated as `optional` and pass the error handling purely to the dApp side.

Im working in a project that supports multiple chains and gnosis connection throw walletconnect. Because of that issue that only the first chain is the required one gnosis wallets couldn't connect with any other chain other the rist one (ethereum in my case).
I overcome this by changing the initialChain prop of the RainbowKitProvider component when a user changes a network in my app. Would be better if, by attempting a connection from the gnosis side, the wallet swaps to the right network on the viem/wagmi side. But at least, while we dont have a better solution, with this is possible to connect. The user only need to make sure to be in the right network on my app side before attempting a connection from the gnosis side.

**Comment by positonic** [comment]
A year later is this still an issue? I can't connect with Rainbow to gnosis.

**Comment by DanielSinclair** [comment]
@positonic Correct. But, Rainbow Wallet will officially support Gnosis within the next few weeks. You can always add a custom chain to our desktop extension as well to use Gnosis today.
