### ISSUE TITLE
[bug] Issues connecting on certain iOS / Android devices

### ISSUE THREAD

**Issue by ZeroTimeDrift** [rainbow-me/rainbowkit#1656]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### RainbowKit Version

1.2.0

### wagmi Version

1.4.5

### Current Behavior

Certain Android / iOS devices clicking wallets on mobile connector result in a dead link / nothing happens. This is a nextjs app running rainbowkit 

### Expected Behavior

Re-direction to the wallet app to initiate connection and signing

### Steps To Reproduce

1. Have specific Android devices or certain iOS devices
2. Open modal
3. Select wallet option
4. Nothing happens

This happens when rainbowkit is embedded on another website and the user is using a mobile device

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://app.kamino.finance/

**Comment by KosmosKey** [comment]
@ZeroTimeDrift We've updated to the latest wagmi + viem version here: https://github.com/rainbow-me/rainbowkit/pull/1653

Is the bug still there ?

**Comment by ZeroTimeDrift** [comment]
I updated just now and the issue is persistent, this happens when rainbowkit is embedded inside an iFrame. You can check here: https://solanacompass.com/ and select the "Ethereum wallet option" on mobile iOS / Android devices, the connect wallet button does not work within the mobile browser itself. I've already given permissions within the iFrame to use it. It works totally fine on https://wallet.moongate.one/ but not when nested on another page.

**Comment by KosmosKey** [comment]
@ZeroTimeDrift on desktop it works fine:
![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/c7c38031-e395-43b6-8c5f-7c97e6f334f3)

I think this is an IOS / Android issue with iframe. Mobile browser apps are blocking third party cookies with iframe and it's very limited. 

Are you able to see if there are any console errors ? This might also be walletconnect issue since on mobile we generate walletconnect uri which redirects to the selected wallet you've chosen. Please see if your project allowlisted domains are correct as well.

These might be a known issue too: https://github.com/WalletConnect/walletconnect-monorepo/issues/289

**Comment by ZeroTimeDrift** [comment]
@KosmosKey thanks for the response, yes it works totally fine on Desktop but we experience issues on mobile. Any idea whether it is a cookie related issue and if so, how can we go around this?

**Comment by KosmosKey** [comment]
@ZeroTimeDrift When using `iframe` it's very limited. Especially if you are using a thirdparty service like walletconnect who deals with a lot of storage.

Here are the things you can do:
1. Try to use wagmi `WalletConnectConnector` and see if `iframe` is blocking it. If it does then it's a problem with the walletconnect on their end. They have a good protection mechanism on their server which browsers are talking to. Here is the [connector](https://wagmi.sh/react/connectors/walletConnect).
2. Try not using `iframe` if possible. Since you will not only face issues with `rainbowkit`, but with other packages too because it's very limited.
3. Use an IOS simulator from `xcode` if you have a mac. Look at what you get from the console and network requests from the simulator. If there are any failures it's easier to test.

**Comment by ZeroTimeDrift** [comment]
I've attempted these, looks like it is some kind of deeplinking / universal link connection issue where it cannot be accessed from within the iFrame itself, is there a way to expose these URLs via some kind of API so I can interface with parent dApps? i.e. take the url string and from my own end use this to execute the deeplink?

**Comment by ZeroTimeDrift** [comment]
I'm digging through wc2 docs for WalletConnectRouter, my hunch is I can use something like this to redirect the calls myself manually though I have no idea where to look for this option within Rainbowkit

**Comment by DanielSinclair** [comment]
@ZeroTimeDrift Since this seems to only occur in isolated iframe usage, this might be out of the scope of what we can optimize/build around. WalletConnect does treat iframes differently as part of their Verify API that validates/authenticates the dApp the wallet is connecting to with the goal of mitigating phishing attacks; not all wallets close the loop and implement this new behavior though, which could explain inconsistent behavior. Mobile browsers also do block certain API usage within an iframe. For example, RainbowKit attempts to trigger a redirect when a user taps a wallet button, and within an iframe context, iOS Safari may block this redirect request because the system attempts to mitigate adware click-jacking and pop-ups. I'll close this for now as it might not be solving we can solve practically, but if you have ideas of a better approach or workaround that we can support, let me know!

**Comment by ZeroTimeDrift** [comment]
> @ZeroTimeDrift Since this seems to only occur in isolated iframe usage, this might be out of the scope of what we can optimize/build around. WalletConnect does treat iframes differently as part of their Verify API that validates/authenticates the dApp the wallet is connecting to with the goal of mitigating phishing attacks; not all wallets close the loop and implement this new behavior though, which could explain inconsistent behavior. Mobile browsers also do block certain API usage within an iframe. For example, RainbowKit attempts to trigger a redirect when a user taps a wallet button, and within an iframe context, iOS Safari may block this redirect request because the system attempts to mitigate adware click-jacking and pop-ups. I'll close this for now as it might not be solving we can solve practically, but if you have ideas of a better approach or workaround that we can support, let me know!

Hey @DanielSinclair,could you expose an API for the mobile URIs on button press? Our wallet is loaded via SDK and so can be loaded on parent page, only the iFrame is locked here and we can pass URIs via postMessage to be executed on the parent
