### ISSUE TITLE
[bug] rainbowkit v2.0.0-beta.2 (+ wagmi v2) breaks previous wallet connect/disconnect/switching behavior

### ISSUE THREAD

**Issue by thatguyintech** [rainbow-me/rainbowkit#1752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0-beta.2

### wagmi Version

2.5.4

### Current Behavior

For context -- I'm working on migrating to wagmi and rainbowkit v2.

With the new versions installed, we're seeing some buggy behavior (on Chrome browser) where:

1. Rainbowkit fails to recognize disconnects when the user changes accounts directly in their browser extension wallet app.
2. Rainbowkit falls back to addresses/accounts that were previously connected when users disconnect in-wallet

Here is a user-facing loom video recording example of (1): https://www.loom.com/share/c595ee28487d4f78acc186d166454ee2
Here is a user-facing loom video recording example of (2): https://www.loom.com/share/3b0bfd71e3bd4002ab577b827d9211dd

Here's how we've set up Rainbowkit v2.0.0-beta.2 in our project: https://gist.github.com/thatguyintech/bd4257e9d77973fe45918b93172b91f9

### Expected Behavior

Our production dependencies are:
- `"@rainbow-me/rainbowkit": "1.0.7"`
- `"wagmi": "1.4.12"`

In our current setup, rainbowkit will not assume that the next connected wallet should be a fallback, and instead will ask users to explicitly re-connect and re-sign if an account change is detected: https://www.loom.com/share/7150350759834245baec637ad94c58a8

### Steps To Reproduce

1. upgrade wagmi + rainbowkit to v2
2. connect wallet
3. try switching accounts from within the wallet browser extension -> see previous account persisted (this might be chrome browser only?)
4. try disconnecting accounts from within the wallet extension -> see next previously-connected account connected now

**Comment by KosmosKey** [comment]
@thatguyintech Thanks for reporting this. We will look into this and give you an update as soon as possible 👍

**Comment by KosmosKey** [comment]
@thatguyintech Just looked into this issue and it seems like it's also happening in rainbowkit version `1.0.7` with wagmi version `1.4.12` on my end:

https://github.com/rainbow-me/rainbowkit/assets/53529533/75002c48-2690-4837-971a-c2920a4f6497

I also see that you have [this](https://gist.github.com/thatguyintech/bd4257e9d77973fe45918b93172b91f9#file-walletconnectandverify-tsx-L48-L55) `useEffect` hook which handles the disconnect part. 

Keep in mind that wagmi v2 also handle multiple connection intances meaning if connect to metamask and later connect with rainbow wallet then you would have to disconnect two times in some casess due to multiple connection instances.

I'm happy to look at your specific issue not sure since i'll have to look at your `useWalletState` hook and see how you handle `notConnected` logic. You can also try using `connector.emitter.on` like we do with [sign-in with ethereum](https://github.com/rainbow-me/rainbowkit/blob/beta/packages/rainbowkit/src/components/RainbowKitProvider/AuthenticationContext.tsx#L95-L110)

**Comment by KosmosKey** [comment]
@thatguyintech Were you able to figure out what the issue was ?

**Comment by thatguyintech** [comment]
Hey @KosmosKey! Really appreciate you taking a look at this -- we can close this thread for now as I agree that there might be some differences in how we expect wagmi v1 vs wagmi v2 to work, so the issue is probably due to how we've written some of the upgrade code.

We're going to punt on upgrading for now and come back to it a later time when we can dig in a little deeper.
