### ISSUE TITLE
[bug] Rainbowkit doesn't accommodate when using mock connector

### ISSUE THREAD

**Issue by oxSaturn** [rainbow-me/rainbowkit#1863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.2

### wagmi Version

2.5.7

### Current Behavior

I'm trying to use [mock connector](https://wagmi.sh/react/api/connectors/mock#import) for testing, only to find that rainbowkit doesn't really support it as clicking the connect button will call out a modal, instead of connecting to the mock account.

### Expected Behavior

Clicking connect button to connect to the mock account.

### Steps To Reproduce

1. visit the stackbliz link, as you can see in that example, I've set `connections` to a `mock` connector.
2. Click `Connect Wallet`, rainbowkit will show a modal instead of connecting to the mock account

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://stackblitz.com/edit/vitejs-vite-ed6kx1?file=src%2FApp.tsx

### Anything else?

I'm not sure if rainbowkit should handle this or not, but if it's not handling the mock, then we'll likely need to place another connect button on the page to connect to mock account for testing purposes.

**Comment by magiziz** [comment]
@oxSaturn Thanks for raising this issue.

The `Connect Wallet` button shouldn't call the `mock` connector since the button is only responsible for opening the connect modal itself.

If you would like `mock` connector to be called during on click then you need to create your own connect button, just like you did for the `click to connect mock` one.

**Comment by oxSaturn** [comment]
> @oxSaturn Thanks for raising this issue.
> 
> The `Connect Wallet` button shouldn't call the `mock` connector since the button is only responsible for opening the connect modal itself.
> 
> If you would like `mock` connector to be called during on click then you need to create your own connect button, just like you did for the `click to connect mock` one.

Do you think it makes sense for rainbowkit to include such a button? I mean, the ConnectButton to open the modal would be useless in e2e test cases, as you can't connect your wallet without wallet extensions installed which unfortunately is not easy as far as I can see. Replacing it with another ConnectButton but connected to mock connector would be more reasonable in such case IMO.

Sure I can define one myself, just want to discuss the possibility here.

**Comment by magiziz** [comment]
@0xartcro We could try to look into this and expose a such button for testing purposes, but we'll have a look into it.

You can do unit test with wagmi like we do [here](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/ChainModal/ChainModal.test.tsx#L9-L28).

What i would also suggest doing is looking at our [WalletButtton](https://www.rainbowkit.com/docs/wallet-button) component, since that provides on click connect effect, which is what you're looking for.

**Comment by oxSaturn** [comment]
> @0xartcro We could try to look into this and expose a such button for testing purposes, but we'll have a look into it.
> 
> You can do unit test with wagmi like we do [here](https://github.com/rainbow-me/rainbowkit/blob/main/packages/rainbowkit/src/components/ChainModal/ChainModal.test.tsx#L9-L28).
> 
> What i would also suggest doing is looking at our [WalletButtton](https://www.rainbowkit.com/docs/wallet-button) component, since that provides on click connect effect, which is what you're looking for.

I'm doing e2e test with playwright, so the example with testing library won't work for me. Anyway, thanks for the suggestion, I'll give WalletButton a try.
