### ISSUE TITLE
[bug] <Reject WalletConnect on mobile, the QrCode not refresh and scan it again no response>

### ISSUE THREAD

**Issue by MickWang** [rainbow-me/rainbowkit#1878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.2

### wagmi Version

2.0.2

### Current Behavior

<img width="1512" alt="image" src="https://github.com/rainbow-me/rainbowkit/assets/6647774/bd6e7b12-f21d-4407-acd7-bf75af64ff67">

### Expected Behavior

After reject connection, the qrcode on conection modal will refresh automatically.

**Comment by magiziz** [comment]
@MickWang This is a normal behaviour with WalletConnect. If you reject the session it can't be used anymore. We're working on fixing this in the long term with universal links instead of deep links (what we're using now). There is also a similar issue here: https://github.com/rainbow-me/rainbowkit/issues/1336

**Comment by MickWang** [comment]
> @MickWang This is a normal behaviour with WalletConnect. If you reject the session it can't be used anymore. We're working on fixing this in the long term with universal links instead of deep links (what we're using now). There is also a similar issue here: #1336

can we catch the exception when reject the connection on mobile wallet apps, and refresh the connect modal or tell users to refresh the page and tray again?

**Comment by magiziz** [comment]
@MickWang Yeah we're thinking of doing that. We'll find a way to simplify this a bit more so it's less confusing 🙏
