### ISSUE TITLE
[bug] modal windows snaps to the bottom in device mode in chrome

### ISSUE THREAD

**Issue by criogennn** [rainbow-me/rainbowkit#1891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.2

### wagmi Version

2.5.12

### Current Behavior

![image](https://github.com/rainbow-me/rainbowkit/assets/108073234/2a3f125a-574e-42d3-a5bd-d76f282aeb56)

in device mode

### Expected Behavior

![image](https://github.com/rainbow-me/rainbowkit/assets/108073234/3c1ec87a-1cca-4336-b821-859f80245dcf)

in normal mode

### Steps To Reproduce

toggle device mode in chrome

### Anything else?

it's same resolution for both

**Comment by magiziz** [comment]
@criogennn It's always been like this. If you open inspect element and lower the window size it will snap at the bottom because it's going to be marked as "responsive" mode. You need to be on mobile in order to get the full mobile view and not play with it on desktop.

Desktop version should work totally fine unless you open it in device mode.

**Comment by criogennn** [comment]
> @criogennn It's always been like this. If you open inspect element and lower the window size it will snap at the bottom because it's going to be marked as "responsive" mode. You need to be on mobile in order to get the full mobile view and not play with it on desktop.
> 
> Desktop version should work totally fine unless you open it in device mode.

oh didnt know this, thx
