### ISSUE TITLE
[bug] MetaMask WalletButton does not target MetaMask when competing injected providers set (e.g. Phantom)

### ISSUE THREAD

**Issue by guyton-cb** [rainbow-me/rainbowkit#1894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.2

### wagmi Version

2.5.6

### Current Behavior

There is some odd behavior when have multiple injected connectors similar to MetaMask. If I have multiple injected providers competing with MM, the WalletButton for MM does not respond, when clicked nothing happens. 

Potential Issue:
- The connector for MM is targeting metamask injected connector but in the cases where other injected providers are not overriding MM it stalls.  e.g in Rabby case they refer to it as "Rabby is in use and Metamask is banned", but Phantom (and others) does not have this feature. 
  **- we may need to use a different connector or find if any issues post the eip6963. i assume the Rainbowkit connectors and injected connects are bumping heads because within the ConnectButton everything works fine**  

Potential Enhancements:
- bubble errors from wallet connectors. This would allow clients to know when something fishy going on and can handle potential errors accordingly. A `try/catch` around the connect should be cool.  
 

### Expected Behavior

ConnectButton for MetaMask targets MetaMask when clicked. 

### Steps To Reproduce

Steps to reproduce:
- install MetaMask and Phantom chrome extension. set up a burner (or log in)
- click MetaMask WalletButton 
- nothing happens

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://rainbowkit-example-rainbowdotme.vercel.app/

**Comment by magiziz** [comment]
There are some cases where EIP-1193 wallets are overriding each other, but it doesn't seem like it's doing nothing. At least when i have Phantom and MetaMask enabled:

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/485a2a68-12cf-4e38-b009-0dc5e47ad4fd)

Can you please share a small repro example with code ?

**Comment by guyton-cb** [comment]
I assume the `Wallet Buttons` on the docs page is implemented the same on the example app https://rainbowkit-example-rainbowdotme.vercel.app/

Some times it works for me on the docs site, and some times stalls. In the cases where i have only MM/Phantom it works fine on the docs site but not when i use a Custom WalletButton. I am currently debugging now to get more insights. 

Current setup:
- install 3 wallets: rabby, metamask, phantom
- rabby is set `MetaMask is in use and Rabby is banned`
- clicking MM does nothing

**Comment by magiziz** [comment]
@guyton-cb I can reproduce this on my end. This is happening because rabby wallet overrides metamask. This is happening for many wallets like zerion, coinbase and others. Let me quickly see if i can get a quick fix and get back to you.

**Comment by magiziz** [comment]
@guyton-cb Just found out that this one seems to be out of our control. Rabby wallet appends it's own data and overrides MetaMask's data / functions. 

This is very normal since a lot of these wallets do the same thing, but we can ignore some of them and not all of them. RainbowKit v1 also  has faced with the same issue until we've introduced EIP-6963 to the connect modal, we'll eventually do the same thing for `WalletButton`.

Meanwhile what i would suggest doing is using our connect modal since it does provide support for EIP-6963 like Rabby and MetaMask, but you might get the same issue just very rare.

Hopefully this makes sense and we're just a wrapper around `wagmi` so this is something that's out of our control and the best thing you can do is not have your Rabby wallet enabled by the time your connecting your wallet.

Lmk if this is makes sense 🙏

**Comment by guyton-cb** [comment]
Make sense to me. I actually ran into this exact same issue building my own connect flow using wagmi, it's what lead me to try out Rainbowkit to see if yall had a fix with custom btns. 

For now, Ill use the connect modal. Thanks!

**Comment by magiziz** [comment]
@guyton-cb Gotcha. Yeah lmk if you face any other issues, but we'll support EIP-6963 for WalletButton near future after `wagmi` fixes some stuff on their end.
