### ISSUE TITLE
Unable to connect to Argent Wallet

### ISSUE THREAD

**Issue by jtfirek** [rainbow-me/rainbowkit#1914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

^2.0.0

### wagmi Version

^2.5.7

### Current Behavior

When connecting to our dapp at ether.fi - users with argent wallet installed - rainbowkit doesn't seem to be recognizing that the user has the wallet.

I am getting the same behavior from the rainbowkit site as well:
<img width="1258" alt="Screenshot 2024-04-03 at 1 12 18 PM" src="https://github.com/rainbow-me/rainbowkit/assets/106350168/c26ec659-58c4-46de-b2b2-08204c8a1f40">

### Expected Behavior

User connects their wallet

### Steps To Reproduce

Navigate to https://www.rainbowkit.com/docs/introduction and try to connect with argent wallet installed

**Comment by magiziz** [comment]
@jtfirek This is an known issue with Argent x wallet. The wallet browser seems to be crashing if it's being used with wagmi. 

Due to that we only support mobile app via WalletConnect QR code. I also attached an image of it failing if we were to use the browser version.

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/0ca68ba8-55f8-4dbc-ba6b-6365331e4d51)

This is also something that's out of our control since those wallets decide themselves how the basic functionality should be.

**Comment by jtfirek** [comment]
Thanks!
