### ISSUE TITLE
[bug] Coinbase wallet QR code scan not showing prompt consistently

### ISSUE THREAD

**Issue by mypalvikram** [rainbow-me/rainbowkit#1994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.6

### wagmi Version

2.5.22

### Current Behavior

When scanning the Coinbase Wallet QR code, the prompt does not appear 100% of the time. When it does appear, if you do not accept or cancel accidentally it does not show back up on the rescan. It does seem to prompt you again after a certain amount of time.

### Expected Behavior

Expect the prompt to be shown 100% of the time when scanning and without delay between cancelled prompts.

### Steps To Reproduce

Scan the Coinbase QR code, wait for the prompt to appear in the app, and then hit cancel. Attempt to rescan and the prompt does not appear.

**Comment by DanielSinclair** [comment]
@mypalvikram This is actually an issue with Coinbase Wallet that we have since reported. I'd recommend you update to RainbowKit [2.1.0](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%402.1.0) which supports an alternative connection approach for Coinbase, and works a bit better with the Coinbase Wallet limitations.
