### ISSUE TITLE
[bug] SafeWallet doesn't appear in list of wallet in RainbowKit modal

### ISSUE THREAD

**Issue by makiBaraba** [rainbow-me/rainbowkit#2197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.0.0

### wagmi Version

2.11.2

### Current Behavior

When I add safeWallet to the rest of the rainbowkit config. 
Safe wallet connection is not appearing on RainbowKit modal. Also, when I try to open it inside iframe on safe wallet site, also doesn't work.

Safe wallet has an option, that you can open app like "Custom app", when I paste the link of my dapp, there is message "The app doesn't support Safe App functionality".

### Expected Behavior

Expected behavior is that, it should work according the guide you have on your official docs.

### Steps To Reproduce

1. Added safeWallet to many wallets which are working just fine
2. https://app.safe.global/ going to this website
3. On section Apps -> Custom apps
4. In the modal, in input field "Safe app url", entering the build of my app, I got error "The app doesn't support Safe App functionality"

**Comment by DanielSinclair** [comment]
I believe the issue is that you haven't included a Manifest file, which Safe requires to load the dApp on their end. Reference Safe's docs [here](https://help.safe.global/en/articles/145503-how-to-create-a-safe-app-with-safe-apps-sdk-and-list-it#:~:text=are%20already%20satisfied.-,Manifest,-It%27s%20mandatory%20that) and our example manifest [here](https://github.com/rainbow-me/rainbowkit/blob/1785c6c301aa0661964da3dcc31981b27f3234fa/packages/example/public/manifest.json#L3)
