### ISSUE TITLE
[bug] Getting multiple errors when wallet gets injected.

### ISSUE THREAD

**Issue by brijeshagal** [rainbow-me/rainbowkit#2231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

2.2.0 (latest)

### wagmi Version

2.12.25 (latest)

### Current Behavior

This is an intermittent issue but has been coming a lot of times recently. Seems like some sort of caching related issue.
The error message can be seen in the console ss below. 
<img width="517" alt="image" src="https://github.com/user-attachments/assets/10fd3e07-c264-41b0-a78a-0f8346bfb3f1">

Additional Info: There are multiple wallets installed like rabby, safepal and metamask. And pocket universe is also working on top of it.

### Expected Behavior

Connection should work perfectly fine. These method calls in the error console should not fail.

### Steps To Reproduce

Not sure what suddenly started this. We have two deployed links, and one of them fails but everything works fine in the other one. Maybe there is some storage issue.

**Comment by DanielSinclair** [comment]
@brijeshagal These actually look like errors coming from the extensions interacting with each other, rather than Rainbow. Try to disable all of the EVM extensions except MetaMask as an example, and you should see this resolve. This is something we can't fix directly because it exists within the inpage scripts of the extensions.
