### ISSUE TITLE
[bug] No Feedback When Calling signMessage on iOS When In Do Not Disturb

### ISSUE THREAD

**Issue by nickcherry** [rainbow-me/rainbowkit#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.5

### Current Behavior

When calling signMessage within Safari on an iOS device that is in Do Not Disturb mode, the message-to-be-signed is queued in the wallet app (e.g. Rainbow, Metamask), but the user receives no feedback. 

### Expected Behavior

I would expect the connected wallet (e.g. Rainbow, MetaMask) to be launched / brought to the foreground, similar to the experience of connecting a wallet. See also https://github.com/rainbow-me/rainbowkit/issues/387.

### Steps To Reproduce

1. In Safari on an iOS device, navigate to https://neon-griffin-f8c8b4.netlify.app/
2. From the iOS Control Center, enable Do Not Disturb mode.
3. Connect to Rainbow or MetaMask.
4. Press "Sign Message" and observe that there is no feedback.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/nickcherry/rainbowkit-test

**Comment by markdalgleish** [comment]
I wasn't able to reproduce this on an iPhone 12 Pro running iOS 15.5, even using the link that you shared. Are you still experiencing this issue?

**Comment by markdalgleish** [comment]
In your video you're not being taken to the native app when tapping "Sign Message". It works for me using the link you shared.

In your original issue it says you're running RainbowKit v0.1.0 but the deep linking fixes were published later than this. Have you since upgraded RainbowKit in your example? If so, can you try disconnecting and reconnecting your wallet? This ensures the WalletConnect local storage value for deep linking is set correctly. It's called `WALLETCONNECT_DEEPLINK_CHOICE` if you want to debug further.

**Comment by nickcherry** [comment]
Yeah, this is with RainbowKit v0.1.0, so that is a good point. This is probably moot given the deeplink change. Gonna close this issue out.
