### ISSUE TITLE
[bug] TypeError when selecting Coinbase Wallet 

### ISSUE THREAD

**Issue by JamieLottering** [rainbow-me/rainbowkit#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.2.4

### wagmi Version

0.4.11

### Current Behavior

Clicking on Coinbase Wallet as an option in the Connect Wallet modal does nothing and triggers this error in the console:
```
TypeError: extension.disableReloadOnDisconnect is not a function
    at CoinbaseWalletSDK.makeWeb3Provider (CoinbaseWalletSDK.js?b21f:91:1)
    at CoinbaseWalletConnector.getProvider (wagmi-core-connectors-coinbaseWallet.esm.js?1a17:144:67)
    at async CoinbaseWalletConnector.connect (wagmi-core-connectors-coinbaseWallet.esm.js?1a17:74:1)
    at async connect (wagmi-core.esm.js?19bf:139:1)
```

Coinbase Wallet Extension:
Version
2.18.1
Updated
June 8, 2022

### Expected Behavior

Clicking 'Coinbase Wallet' opens the Coinbase Wallet connect extension window

### Steps To Reproduce

Use rainbowkit v0.2.4
Use wagmi v0.4.11
Use Coinbase Wallet extension 2.18.1

Click `Coinbase Wallet` 
![image](https://user-images.githubusercontent.com/134010/173107377-f043c5af-ea07-4b12-9309-8d31ef600d69.png)

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://eightbit-nxf3wjbet-lets-go.vercel.app/

### Anything else?

NextJS, Vercel, Chrome 102.0.5005.61

**Comment by markdalgleish** [comment]
I ran into this issue also. Turns out it happens when the Coinbase Wallet SDK is running against an older version of the browser extension.

I spoke with their team yesterday and they've pushed out a fix in [@coinbase/wallet-sdk@3.3.0](https://github.com/coinbase/coinbase-wallet-sdk/releases/tag/v3.3.0). It now checks whether `extension.disableReloadOnDisconnect` exists before calling it. You can see the specific PR fixing the issue here: https://github.com/coinbase/coinbase-wallet-sdk/pull/575.
