### ISSUE TITLE
[bug] Rainbow doesn't redirect back to app after sign a message

### ISSUE THREAD

**Issue by enesozturk** [rainbow-me/rainbowkit#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.3.3

### wagmi Version

0.4.12

### Current Behavior

For any message signing, a Rainbow screen shows and asks to open the Rainbow app, after signing a message, the app doesn't redirect me to the browser again. I need to go back manually. After going back to the browser, I still see Rainbow's screen. I needed to go back to the previous screen to see my app.

### Expected Behavior

- Expected the Rainbow to redirect to the browser app.
- Expected the Rainbow screen route back to my app. 

### Steps To Reproduce

- Open [showtime.xyz](https://showtime.xyz/) on mobile browser
- Click "Sign In"
- Select "Connect Wallet"
- Select Rainbow
- Confirm (it will go back to the browser app again)
- It will redirect to Rainbow again to sign a message.
   - Here after signing, it doesn't goes back to the browser app.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://showtime.xyz/

### Anything else?

In the video, I needed to try again, in the first confirmation, the Rainbow modal didn't disappear;
https://user-images.githubusercontent.com/19428358/174833039-862e6d88-05d8-4cf0-b21e-90249dc80d53.MP4

**Comment by JamieLottering** [comment]
+1 - makes it almost impossible to sign a message on our site because the pending promise listening for the response to the message is cleared because the page changed

**Comment by enesozturk** [comment]
This is the Google Chrome version. This time there are some more issues;
- At first, I have one section opened. (Showtime app)
- I confirm, it redirects me to Chrome but a new, blank section is opened, I needed to close it. (Even users might not understand they are in a new blank section, they might think app is blown)
- Redirected me for sign message, signed. 
- Then I manually needed to open the GC again.
- Go back manually.
https://user-images.githubusercontent.com/19428358/174857075-c44fada3-0a20-40a8-bb3e-1d6f3de3fa98.MP4

**Comment by markdalgleish** [comment]
I've been able to reproduce this using wagmi directly without RainbowKit. They have a Sign-In with Ethereum demo on their docs site (https://wagmi.sh/examples/sign-in-with-ethereum) where I can see the same problem. I've been able to reproduce this with other wallets too.

This seems like it could be related to another issue I've raised with WalletConnect: https://github.com/WalletConnect/walletconnect-monorepo/issues/1165. Redirecting to universal links via JS doesn't work correctly if it's not directly tied to a user action, or if it happens too long after the click event due to API calls etc.

@enesozturk This looks like there's a seperate issue in Chrome on iOS (and potentially other non-Safari browsers) when opening universal links in a new window via JS. I've opened a new issue to track this: #524.

**Comment by nickbytes** [comment]
@enesozturk re: Coinbase wallet issue, just tested this using https://rainbowkit-example.vercel.app/, which is our testing app that gets deployed w/ every update to the `main` branch, and I'm not able to reproduce this.

Can you share some more minimal reproducible example (w/ source code) rather than just the showtime.xyz url? It's difficult to tell what might be happening there without seeing code.

Let's also try to keep this issue focused on redirect/deeplink behavior. Happy to keep chatting about this in issue I just opened for ya: https://github.com/rainbow-me/rainbowkit/issues/531

**Comment by enesozturk** [comment]
@nickbytes I tried [https://rainbowkit-example.vercel.app/](https://rainbowkit-example.vercel.app/ ) but it seems the same on it. Here is a video recording. Also checked Coinbase Wallet app updates but looks up to date already.

https://user-images.githubusercontent.com/19428358/175231919-baaf701a-c00e-4c6e-91bf-931b0021e0f1.MP4

**Comment by markdalgleish** [comment]
As I understand it, this issue has been resolved on Showtime's end and is to do with app linking on iOS needing to be directly and immediately tied to a user action. Showtime now presents users with a button to manually trigger the signature request rather than automatically triggering the request after connecting.

I've since added some documentation to the WalletConnect site that goes into more detail on this constraint and explains how to manage it: https://docs.walletconnect.com/mobile-linking#ios-app-link-constraints
