### ISSUE TITLE
[bug] modal style application on <body> tag breaks certain layouts

### ISSUE THREAD

**Issue by el-ranye** [rainbow-me/rainbowkit#609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.4.4

### wagmi Version

0.5.11

### Current Behavior

When loading any rainbow kit modal on a screen where `body` is styled with a `max-width` and `margin: 0 auto` (as a means to center the column), and the viewport is larger than the max-width, rainbow kit's application of padding and margin styles shifts the content in the background.

While this doesn't cause any issues with the actual connecting of the wallet, it does create an experience that feels "off" -- not ideal when users are taking a sensitive action like connecting their wallet.

### Expected Behavior

Opening a rainbow kit modal should not cause any content shift on a site's existing content, regardless of the site's existing body styles.

### Steps To Reproduce

1. Load [terraformexplorer.xyz](https://www.terraformexplorer.xyz/)
2. The body has a max-width of 1600px, so you'll either need to expand your viewport wider than 1600px OR modify the body style to have a max-width less than your current viewport
3. Click `Connect Wallet`

Observe that the content in the background shifts:

https://user-images.githubusercontent.com/96595075/180608927-8da85ce1-77db-4bd8-b485-d307c258e103.mov

### Anything else?

Confirmed this is happening on at least latest Chrome and latest Firefox

**Comment by el-ranye** [comment]
fwiw, I was able to work around this by moving the max-width declaration off the body and to a child div.

**Comment by markdalgleish** [comment]
I'm not sure this can be automatically avoided. This is due to our use of [react-remove-scroll](https://npmjs.com/package/react-remove-scroll) which prevents the body from being scrollable while modals are open. While doing this, it also adds a `margin-right` style to the body element to reserve space for the scrollbar after it disappears (since the page can't be scrolled anymore). If this isn't done, the page content can move slightly when opening and closing the modals.

I think your workaround of keeping layout styles decoupled from the body tag would be the recommended approach.
