### ISSUE TITLE
[bug] Installing repo dependencies using `yarn install` or `npm install` always fails

### ISSUE THREAD

**Issue by 0xpApaSmURf** [rainbow-me/rainbowkit#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.6.0

### wagmi Version

n/a

### Current Behavior

Attempting to install the dependencies on the repository always fails.

`yarn install` fails.

### Expected Behavior

`yarn install` succeeds.

### Steps To Reproduce

Fresh checkout of the repo.

```sh
$ yarn install
...
error rainbowkit/node_modules/@lavamoat/preinstall-always-fail: Command failed.
Exit code: 1
Command: echo "Don't run npm lifecycle scripts by default, whitelist them with @lavamoat/allow-scripts" && exit 1
Arguments:
```

### Anything else?

This fails due to the inclusion of the `@lavamoat/preinstall-always-fail`, which in itself fails to install itself during the install step.

**Comment by markdalgleish** [comment]
This repo uses [pnpm](https://pnpm.io) rather than yarn or the official npm client.

The [@lavamoat/preinstall-always-fail](https://www.npmjs.com/package/@lavamoat/preinstall-always-fail) package deliberately breaks the install step if its preinstall script is allowed to run. This serves as a test case to ensure we've disabled package install scripts correctly.

The install step works in pnpm because we've configured pnpm's [`onlyBuiltDependencies` option](https://pnpm.io/package_json#pnpmonlybuiltdependencies) to only allow install scripts for [esbuild,](https://esbuild.github.io) which you can see in our package.json: https://github.com/rainbow-me/rainbowkit/blob/7b3ed26b4892539d58bd7d6a6bc5011304da97d9/package.json#L81-L850

**Comment by 0xTARC** [comment]
@markdalgleish what if pnpm install still fails?

After cloning the repo fresh, installing pnpm (`npm i -g pnpm`), and running `pnpm install`, it fails with

```
ERR_PNPM_PREPARE_PKG_FAILURE  Command failed with exit code 1: npm install
```

Tried on a WSL environment and repro'd as well

If I configure lavamoat as you would with just npm:

```
npm i -D @lavamoat/allow-scripts
npx --no-install allow-scripts setup
```

and add
```json
  "lavamoat": {
    "allowScripts": {
      "esbuild": true
    }
  }
```
to `package.json`

then `npm install` succeeds, but `pnpm install` still fails with the same error
```
ERR_PNPM_PREPARE_PKG_FAILURE  Command failed with exit code 1: npm install
```

any ideas? no special global setup you all have done?

I would love to start contributing but I can't get this code to build 🙃
