### ISSUE TITLE
[bug] ENS name not displaying

### ISSUE THREAD

**Issue by RichieRob** [rainbow-me/rainbowkit#848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.7.3

### wagmi Version

0.6.8

### Current Behavior

When connecting to site ENS name doesn't display.

<img width="1710" alt="image" src="https://user-images.githubusercontent.com/110105361/198016055-05868ff2-39b8-4b57-8190-c95b027fe0b8.png">

### Expected Behavior

ENS name should display for example in uniswap
Example of ENS name resolving on Uniswap
<img width="2029" alt="image" src="https://user-images.githubusercontent.com/110105361/198016612-09b8131a-27de-4909-bbc9-507c7f60009c.png">

### Steps To Reproduce

Log in to rainbowkit.com with account that has an ENS name set.

### Anything else?

Noticed this issue when running the example code locally.

**Comment by adbario** [comment]
Did you just purchase the ENS name? `wagmi` has 24 hrs stale time by default, which means you might not get the name for new domains if you tried to fetch it before the purchase and setup.

**Comment by RichieRob** [comment]
I've had the ENS name for 12 months or more.

From further research it looks as it is an alchemy error. It exists both locally and when logging into rainbowkit.com. I got it working with infura.

**Comment by 0xAskar** [comment]
to add to these answers. I used infura instead of alchemy (not sure if this was the problem), but most importantly i used @adbario comment about the wagmi local storage. i went to my local storage and deleted all storage from wagmi and then reloaded and that showed the ens

the documentation should include notes about this instead of letting users struggle to figure out why it doesn't work at times.
