### ISSUE TITLE
[bug] wallet area occupies less than 340px, the information will wrap after connecting

### ISSUE THREAD

**Issue by 0x3Anthony** [rainbow-me/rainbowkit#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.8.1

### wagmi Version

0.9.4

### Current Behavior

When the wallet area occupies less than 340px, the information will wrap after connecting
![image](https://user-images.githubusercontent.com/100060836/209446434-e79f50b8-0f8f-47f7-b455-11e0d16e0588.png)

### Expected Behavior

It is hoped that no newlines can be provided or the props interface can be provided so that developers can customize the style to override the official default style.

### Anything else?

![image](https://user-images.githubusercontent.com/100060836/209446993-af6e1003-8e7a-45df-a1b6-4c0e1f38da60.png)

**Comment by DanielSinclair** [comment]
Hi @0x3Anthony. The solution for this isn't ideal because it requires a bit more work, but we implemented a `ConnectButton.Custom` API for this very problem. Outside of the typical implementation, this is the recommended approach. Read the docs [here](https://www.rainbowkit.com/docs/custom-connect-button)
